[build]
  base = ""
  publish = "dist/bank-transaction/browser"  # Replace with your actual build output folder
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
